# Generated by Django 5.0.3 on 2024-04-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='difficulty',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
