# Generated by Django 4.2.3 on 2024-07-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studyapp', '0002_flashcards_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
